### ISSUE TITLE
Version of theme which does not included auto hiding of channel list.

### ISSUE THREAD

**Issue by EvilSpark** [A-User-s-Discord-Themes/Bash#3]
Can you add a version with it disabled?
It really shakes the mind whenever it happens.

**Comment by EvilSpark** [comment]
Same for members list

**Comment by MEXdave1997** [comment]
Kind of second this. Or maybe just make a way for us to toggle it in the settings if possible(?)

**Comment by Juby210** [comment]
![image](https://user-images.githubusercontent.com/31005896/82729851-46657500-9cfb-11ea-80fc-2899b9484151.png)
```css
@import url("https://a-user-s-discord-themes.github.io/Bash/external%20plugins/no-compact-discord.css");
```
@UPPERCASEuser close it
